name: Deploy Backend and Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest
    outputs:
      build-artifact: ${{ steps.upload-backend.outputs.artifact }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node for backend
        uses: actions/setup-node@v4
        with:
          node-version: 22.11.0
          cache: "npm"
          cache-dependency-path: healthmate-backend-public/package-lock.json

      - name: Install backend dependencies
        working-directory: healthmate-backend-public
        run: npm install --force

      - name: Import .env
        run: |
          cat <<'EOF' > healthmate-backend-public/.env
          ${{ secrets.BACKEND_ENV_PRODUCTION }}
          EOF

      - name: Build backend
        working-directory: healthmate-backend-public
        run: npm run build-vps

      - name: Upload backend build artifact
        id: upload-backend
        uses: actions/upload-artifact@v4
        with:
          name: backend-build
          path: healthmate-backend-public/dist

  build-frontend:
    runs-on: ubuntu-latest
    outputs:
      build-artifact: ${{ steps.upload-frontend.outputs.artifact }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node for frontend
        uses: actions/setup-node@v4
        with:
          node-version: 22.11.0
          cache: "npm"
          cache-dependency-path: healthmate-frontend-public/health-mate/package-lock.json

      - name: Install frontend dependencies
        working-directory: healthmate-frontend-public/health-mate
        run: npm install --force

      - name: Import .env
        run: echo "${{ secrets.FRONTEND_ENV_PRODUCTION }}" > healthmate-frontend-public/health-mate/.env

      - name: Build frontend
        working-directory: healthmate-frontend-public/health-mate
        run: npm run build

      - name: Upload frontend build artifact
        id: upload-frontend
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: healthmate-frontend-public/health-mate/dist
